### ISSUE TITLE
We should report a nice error when a database connection fails

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp-core#1]
Current error, when for example a password is wrong, is buried in some stack trace. 

```
13:22:24.329 [vamp-core-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
13:22:25.251 [vamp-core-akka.actor.default-dispatcher-2] ERROR akka.actor.OneForOneStrategy - FATAL: password authentication failed for user "postgres"
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:164) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.11-2.3.9.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11
```

**Comment by plamola** [comment]
Fixing it with HI endpoint
