### ISSUE TITLE
ClassCastException: io.vamp.common.notification.NotificationErrorException cannot be cast to io.vamp.core.persistence.ArtifactResponseEnvelope

### ISSUE THREAD

**Issue by metskem-rabo** [magneticio/vamp-core#9]
When trying to get the blueprints at /api/v1/blueprints the following shows up in the daemon.log:
```
java.util.concurrent.ExecutionException: dispatch.StatusCode: Unexpected response status: 404
        at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:342) ~[vamp-core.jar:0.7.8]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.abort(NettyAsyncHttpProvider.java:1418) ~[vamp-core.jar:0.7.8]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2257) ~[vamp-core.jar:0.7.8]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1228) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[vamp-core.jar:0.7.8]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[vamp-core.jar:0.7.8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]
Caused by: dispatch.StatusCode: Unexpected response status: 404
        at dispatch.OkHandler$class.onStatusReceived(handlers.scala:37) ~[vamp-core.jar:0.7.8]
        at dispatch.OkFunctionHandler.onStatusReceived(handlers.scala:29) ~[vamp-core.jar:0.7.8]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.updateStatusAndInterrupt(NettyAsyncHttpProvider.java:1560) ~[vamp-core.jar:0.7.8]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2600(NettyAsyncHttpProvider.java:161) ~[vamp-core.jar:0.7.8]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2212) ~[vamp-core.jar:0.7.8]
        ... 27 common frames omitted
15:55:00.786 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure.  Reason: org.h2.jdbc.JdbcSQLException: Column "X2.dialects" not found; SQL statement:
select x2."deployment_fk", x2."name", x2."blueprint_id", x2."sla_reference_id", x2."dialects", x2."id" from "clusters" x2 order by x2."id" [42122-166]
15:55:00.787 | ERROR | io.vamp.common.notification.Notification |                                          | Persistence operation failure.  Reason: java.lang.ClassCastException: io.vamp.common.notification.NotificationErrorException cannot be cast to io.vamp.core.persistence.ArtifactResponseEnvelope
15:55:02.746 | ERROR | io.vamp.common.notification.Notification |                                          | Event query error, check request format.
15:55:02.747 | ERROR | io.vamp.common.notification.Notification |                                          | dispatch.StatusCode: Unexpected response status: 404
```

My vamp-core application.conf has : 

```
  persistence {
    response-timeout = 15 # seconds
    pulse.url = ${vamp.core.pulse-driver.url}
    storage-type: "jdbc" # jdbc or in-memory
    jdbc {
      database-schema-name = ""
      # H2 file db
       slick-driver = "scala.slick.driver.H2Driver$"
       provider = {
        url = "jdbc:h2:///appl/vamp/data/vamp-core-db"
        driver = org.h2.Driver
        connectionPool = disabled
        keepAliveConnection = true
       }
    }
...
```

**Comment by plamola** [comment]
Looks like your vamp-core-db is missing some columns. 
There are some breaking changes in the latest releases.
Please delete your database; vamp will recreate it on startup, with all the necessary bits.

**Comment by metskem-rabo** [comment]
Yup, just stopped core, dropped the DB and started again, works much better.

Tx,
Harry
